version: "3"

services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=astro
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

