env: development
port: 3000
postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: astro
token:
  public_key: age1gr623h7ea9220efad7g6vjdp0vt25edsraqjn4j0ten7yzgf84rsnw55yg
  private_key: AGE-SECRET-KEY-1WRTAN4RLC3PVGTFWNNQEA2SCX37XL9WDSK4UH58M52S2AU8WFUUQHS0C3L
