env: development
port: 3000
postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: astro

token:
  public_key: |
    -----BEGIN PGP PUBLIC KEY BLOCK-----

    mI0EXSWv8QEEANITYzQaR1s2LbZtNZNj9E0xvkdUZ+RzjUdmjiPcUUTTMZ0r56AQ
    GgxRFtb2HOlg7qCFpYJyyzK0glsPV5Fmlt6TMRQiskVH0bk0FnutWK4S3nCynIFF
    +U/IMftmS+fBtcS4wJ2kqn6GPleTGgbPaM/R5KcHRwEUIEPyfLSuNQFdABEBAAG0
    CWRlbW8tdGVzdIjOBBMBCAA4FiEE8L4l7kQJL1kwGGOhLP4w7zUVVhIFAl0lr/EC
    GwMFCwkIBwIGFQoJCAsCBBYCAwECHgECF4AACgkQLP4w7zUVVhLBegP6AlZJBP2y
    jHwSo/t56ww4xBpfikXFD2tzvkJ7QmszOIqh9Bfa2HjvaO2yGVzijMudK++xTKdY
    M1Qo6Crn64vgqSc9crgn0ytVMVEpZ258H6z7qzB5pAETYMbwAaErib7IIrFEKzP7
    R0DayFML/OR0OD/xMv6104U9nIed4IbnF9O4jQRdJa/xAQQA47MvrpYH2/tJzV4h
    LVDBTkEg1AGaE5g4b74lotseEdQxv7bCd1ffqDxQT0xRT8EfpVMtK08Sy628oCyX
    K2De6HymHFGVlXptNCe5XSP7R6ES5PrybD4JwDFwnA0/Hy67l5XgSF5DAuA9X6KR
    RAJwM5koiv9QN/atx3axWGo74zkAEQEAAYi2BBgBCAAgFiEE8L4l7kQJL1kwGGOh
    LP4w7zUVVhIFAl0lr/ECGwwACgkQLP4w7zUVVhKGuwQAkE739R8M0lkzaDp7rCg4
    6kh78Q/x5LSB5vGOlvNa8yRRu5jFqGDQoSDsjMWCc9Ml5XLUeL4svtF/LhXIVcIn
    Ty9N1nD6MIBj7IwTmd/jVpbEeneRBKXxLOmiYJjLrOALAYyn8jNtm2yNsx4l2M/q
    vL7IbSgYhL+c8UMGGgEXcc8=
    =oWe9
    -----END PGP PUBLIC KEY BLOCK----------BEGIN PGP PUBLIC KEY BLOCK-----

    mI0EXSWv8QEEANITYzQaR1s2LbZtNZNj9E0xvkdUZ+RzjUdmjiPcUUTTMZ0r56AQ
    GgxRFtb2HOlg7qCFpYJyyzK0glsPV5Fmlt6TMRQiskVH0bk0FnutWK4S3nCynIFF
    +U/IMftmS+fBtcS4wJ2kqn6GPleTGgbPaM/R5KcHRwEUIEPyfLSuNQFdABEBAAG0
    CWRlbW8tdGVzdIjOBBMBCAA4FiEE8L4l7kQJL1kwGGOhLP4w7zUVVhIFAl0lr/EC
    GwMFCwkIBwIGFQoJCAsCBBYCAwECHgECF4AACgkQLP4w7zUVVhLBegP6AlZJBP2y
    jHwSo/t56ww4xBpfikXFD2tzvkJ7QmszOIqh9Bfa2HjvaO2yGVzijMudK++xTKdY
    M1Qo6Crn64vgqSc9crgn0ytVMVEpZ258H6z7qzB5pAETYMbwAaErib7IIrFEKzP7
    R0DayFML/OR0OD/xMv6104U9nIed4IbnF9O4jQRdJa/xAQQA47MvrpYH2/tJzV4h
    LVDBTkEg1AGaE5g4b74lotseEdQxv7bCd1ffqDxQT0xRT8EfpVMtK08Sy628oCyX
    K2De6HymHFGVlXptNCe5XSP7R6ES5PrybD4JwDFwnA0/Hy67l5XgSF5DAuA9X6KR
    RAJwM5koiv9QN/atx3axWGo74zkAEQEAAYi2BBgBCAAgFiEE8L4l7kQJL1kwGGOh
    LP4w7zUVVhIFAl0lr/ECGwwACgkQLP4w7zUVVhKGuwQAkE739R8M0lkzaDp7rCg4
    6kh78Q/x5LSB5vGOlvNa8yRRu5jFqGDQoSDsjMWCc9Ml5XLUeL4svtF/LhXIVcIn
    Ty9N1nD6MIBj7IwTmd/jVpbEeneRBKXxLOmiYJjLrOALAYyn8jNtm2yNsx4l2M/q
    vL7IbSgYhL+c8UMGGgEXcc8=
    =oWe9
    -----END PGP PUBLIC KEY BLOCK----------BEGIN PGP PUBLIC KEY BLOCK-----

    mI0EXSWv8QEEANITYzQaR1s2LbZtNZNj9E0xvkdUZ+RzjUdmjiPcUUTTMZ0r56AQ
    GgxRFtb2HOlg7qCFpYJyyzK0glsPV5Fmlt6TMRQiskVH0bk0FnutWK4S3nCynIFF
    +U/IMftmS+fBtcS4wJ2kqn6GPleTGgbPaM/R5KcHRwEUIEPyfLSuNQFdABEBAAG0
    CWRlbW8tdGVzdIjOBBMBCAA4FiEE8L4l7kQJL1kwGGOhLP4w7zUVVhIFAl0lr/EC
    GwMFCwkIBwIGFQoJCAsCBBYCAwECHgECF4AACgkQLP4w7zUVVhLBegP6AlZJBP2y
    jHwSo/t56ww4xBpfikXFD2tzvkJ7QmszOIqh9Bfa2HjvaO2yGVzijMudK++xTKdY
    M1Qo6Crn64vgqSc9crgn0ytVMVEpZ258H6z7qzB5pAETYMbwAaErib7IIrFEKzP7
    R0DayFML/OR0OD/xMv6104U9nIed4IbnF9O4jQRdJa/xAQQA47MvrpYH2/tJzV4h
    LVDBTkEg1AGaE5g4b74lotseEdQxv7bCd1ffqDxQT0xRT8EfpVMtK08Sy628oCyX
    K2De6HymHFGVlXptNCe5XSP7R6ES5PrybD4JwDFwnA0/Hy67l5XgSF5DAuA9X6KR
    RAJwM5koiv9QN/atx3axWGo74zkAEQEAAYi2BBgBCAAgFiEE8L4l7kQJL1kwGGOh
    LP4w7zUVVhIFAl0lr/ECGwwACgkQLP4w7zUVVhKGuwQAkE739R8M0lkzaDp7rCg4
    6kh78Q/x5LSB5vGOlvNa8yRRu5jFqGDQoSDsjMWCc9Ml5XLUeL4svtF/LhXIVcIn
    Ty9N1nD6MIBj7IwTmd/jVpbEeneRBKXxLOmiYJjLrOALAYyn8jNtm2yNsx4l2M/q
    vL7IbSgYhL+c8UMGGgEXcc8=
    =oWe9
    -----END PGP PUBLIC KEY BLOCK----------BEGIN PGP PUBLIC KEY BLOCK-----

    mI0EXSWv8QEEANITYzQaR1s2LbZtNZNj9E0xvkdUZ+RzjUdmjiPcUUTTMZ0r56AQ
    GgxRFtb2HOlg7qCFpYJyyzK0glsPV5Fmlt6TMRQiskVH0bk0FnutWK4S3nCynIFF
    +U/IMftmS+fBtcS4wJ2kqn6GPleTGgbPaM/R5KcHRwEUIEPyfLSuNQFdABEBAAG0
    CWRlbW8tdGVzdIjOBBMBCAA4FiEE8L4l7kQJL1kwGGOhLP4w7zUVVhIFAl0lr/EC
    GwMFCwkIBwIGFQoJCAsCBBYCAwECHgECF4AACgkQLP4w7zUVVhLBegP6AlZJBP2y
    jHwSo/t56ww4xBpfikXFD2tzvkJ7QmszOIqh9Bfa2HjvaO2yGVzijMudK++xTKdY
    M1Qo6Crn64vgqSc9crgn0ytVMVEpZ258H6z7qzB5pAETYMbwAaErib7IIrFEKzP7
    R0DayFML/OR0OD/xMv6104U9nIed4IbnF9O4jQRdJa/xAQQA47MvrpYH2/tJzV4h
    LVDBTkEg1AGaE5g4b74lotseEdQxv7bCd1ffqDxQT0xRT8EfpVMtK08Sy628oCyX
    K2De6HymHFGVlXptNCe5XSP7R6ES5PrybD4JwDFwnA0/Hy67l5XgSF5DAuA9X6KR
    RAJwM5koiv9QN/atx3axWGo74zkAEQEAAYi2BBgBCAAgFiEE8L4l7kQJL1kwGGOh
    LP4w7zUVVhIFAl0lr/ECGwwACgkQLP4w7zUVVhKGuwQAkE739R8M0lkzaDp7rCg4
    6kh78Q/x5LSB5vGOlvNa8yRRu5jFqGDQoSDsjMWCc9Ml5XLUeL4svtF/LhXIVcIn
    Ty9N1nD6MIBj7IwTmd/jVpbEeneRBKXxLOmiYJjLrOALAYyn8jNtm2yNsx4l2M/q
    vL7IbSgYhL+c8UMGGgEXcc8=
    =oWe9
    -----END PGP PUBLIC KEY BLOCK----------BEGIN PGP PUBLIC KEY BLOCK-----

    mI0EXSWv8QEEANITYzQaR1s2LbZtNZNj9E0xvkdUZ+RzjUdmjiPcUUTTMZ0r56AQ
    GgxRFtb2HOlg7qCFpYJyyzK0glsPV5Fmlt6TMRQiskVH0bk0FnutWK4S3nCynIFF
    +U/IMftmS+fBtcS4wJ2kqn6GPleTGgbPaM/R5KcHRwEUIEPyfLSuNQFdABEBAAG0
    CWRlbW8tdGVzdIjOBBMBCAA4FiEE8L4l7kQJL1kwGGOhLP4w7zUVVhIFAl0lr/EC
    GwMFCwkIBwIGFQoJCAsCBBYCAwECHgECF4AACgkQLP4w7zUVVhLBegP6AlZJBP2y
    jHwSo/t56ww4xBpfikXFD2tzvkJ7QmszOIqh9Bfa2HjvaO2yGVzijMudK++xTKdY
    M1Qo6Crn64vgqSc9crgn0ytVMVEpZ258H6z7qzB5pAETYMbwAaErib7IIrFEKzP7
    R0DayFML/OR0OD/xMv6104U9nIed4IbnF9O4jQRdJa/xAQQA47MvrpYH2/tJzV4h
    LVDBTkEg1AGaE5g4b74lotseEdQxv7bCd1ffqDxQT0xRT8EfpVMtK08Sy628oCyX
    K2De6HymHFGVlXptNCe5XSP7R6ES5PrybD4JwDFwnA0/Hy67l5XgSF5DAuA9X6KR
    RAJwM5koiv9QN/atx3axWGo74zkAEQEAAYi2BBgBCAAgFiEE8L4l7kQJL1kwGGOh
    LP4w7zUVVhIFAl0lr/ECGwwACgkQLP4w7zUVVhKGuwQAkE739R8M0lkzaDp7rCg4
    6kh78Q/x5LSB5vGOlvNa8yRRu5jFqGDQoSDsjMWCc9Ml5XLUeL4svtF/LhXIVcIn
    Ty9N1nD6MIBj7IwTmd/jVpbEeneRBKXxLOmiYJjLrOALAYyn8jNtm2yNsx4l2M/q
    vL7IbSgYhL+c8UMGGgEXcc8=
    =oWe9
    -----END PGP PUBLIC KEY BLOCK----------BEGIN PGP PUBLIC KEY BLOCK-----

    mI0EXSWv8QEEANITYzQaR1s2LbZtNZNj9E0xvkdUZ+RzjUdmjiPcUUTTMZ0r56AQ
    GgxRFtb2HOlg7qCFpYJyyzK0glsPV5Fmlt6TMRQiskVH0bk0FnutWK4S3nCynIFF
    +U/IMftmS+fBtcS4wJ2kqn6GPleTGgbPaM/R5KcHRwEUIEPyfLSuNQFdABEBAAG0
    CWRlbW8tdGVzdIjOBBMBCAA4FiEE8L4l7kQJL1kwGGOhLP4w7zUVVhIFAl0lr/EC
    GwMFCwkIBwIGFQoJCAsCBBYCAwECHgECF4AACgkQLP4w7zUVVhLBegP6AlZJBP2y
    jHwSo/t56ww4xBpfikXFD2tzvkJ7QmszOIqh9Bfa2HjvaO2yGVzijMudK++xTKdY
    M1Qo6Crn64vgqSc9crgn0ytVMVEpZ258H6z7qzB5pAETYMbwAaErib7IIrFEKzP7
    R0DayFML/OR0OD/xMv6104U9nIed4IbnF9O4jQRdJa/xAQQA47MvrpYH2/tJzV4h
    LVDBTkEg1AGaE5g4b74lotseEdQxv7bCd1ffqDxQT0xRT8EfpVMtK08Sy628oCyX
    K2De6HymHFGVlXptNCe5XSP7R6ES5PrybD4JwDFwnA0/Hy67l5XgSF5DAuA9X6KR
    RAJwM5koiv9QN/atx3axWGo74zkAEQEAAYi2BBgBCAAgFiEE8L4l7kQJL1kwGGOh
    LP4w7zUVVhIFAl0lr/ECGwwACgkQLP4w7zUVVhKGuwQAkE739R8M0lkzaDp7rCg4
    6kh78Q/x5LSB5vGOlvNa8yRRu5jFqGDQoSDsjMWCc9Ml5XLUeL4svtF/LhXIVcIn
    Ty9N1nD6MIBj7IwTmd/jVpbEeneRBKXxLOmiYJjLrOALAYyn8jNtm2yNsx4l2M/q
    vL7IbSgYhL+c8UMGGgEXcc8=
    =oWe9
    -----END PGP PUBLIC KEY BLOCK----------BEGIN PGP PUBLIC KEY BLOCK-----

    mI0EXSWv8QEEANITYzQaR1s2LbZtNZNj9E0xvkdUZ+RzjUdmjiPcUUTTMZ0r56AQ
    GgxRFtb2HOlg7qCFpYJyyzK0glsPV5Fmlt6TMRQiskVH0bk0FnutWK4S3nCynIFF
    +U/IMftmS+fBtcS4wJ2kqn6GPleTGgbPaM/R5KcHRwEUIEPyfLSuNQFdABEBAAG0
    CWRlbW8tdGVzdIjOBBMBCAA4FiEE8L4l7kQJL1kwGGOhLP4w7zUVVhIFAl0lr/EC
    GwMFCwkIBwIGFQoJCAsCBBYCAwECHgECF4AACgkQLP4w7zUVVhLBegP6AlZJBP2y
    jHwSo/t56ww4xBpfikXFD2tzvkJ7QmszOIqh9Bfa2HjvaO2yGVzijMudK++xTKdY
    M1Qo6Crn64vgqSc9crgn0ytVMVEpZ258H6z7qzB5pAETYMbwAaErib7IIrFEKzP7
    R0DayFML/OR0OD/xMv6104U9nIed4IbnF9O4jQRdJa/xAQQA47MvrpYH2/tJzV4h
    LVDBTkEg1AGaE5g4b74lotseEdQxv7bCd1ffqDxQT0xRT8EfpVMtK08Sy628oCyX
    K2De6HymHFGVlXptNCe5XSP7R6ES5PrybD4JwDFwnA0/Hy67l5XgSF5DAuA9X6KR
    RAJwM5koiv9QN/atx3axWGo74zkAEQEAAYi2BBgBCAAgFiEE8L4l7kQJL1kwGGOh
    LP4w7zUVVhIFAl0lr/ECGwwACgkQLP4w7zUVVhKGuwQAkE739R8M0lkzaDp7rCg4
    6kh78Q/x5LSB5vGOlvNa8yRRu5jFqGDQoSDsjMWCc9Ml5XLUeL4svtF/LhXIVcIn
    Ty9N1nD6MIBj7IwTmd/jVpbEeneRBKXxLOmiYJjLrOALAYyn8jNtm2yNsx4l2M/q
    vL7IbSgYhL+c8UMGGgEXcc8=
    =oWe9
    -----END PGP PUBLIC KEY BLOCK----------BEGIN PGP PUBLIC KEY BLOCK-----

    mI0EXSWv8QEEANITYzQaR1s2LbZtNZNj9E0xvkdUZ+RzjUdmjiPcUUTTMZ0r56AQ
    GgxRFtb2HOlg7qCFpYJyyzK0glsPV5Fmlt6TMRQiskVH0bk0FnutWK4S3nCynIFF
    +U/IMftmS+fBtcS4wJ2kqn6GPleTGgbPaM/R5KcHRwEUIEPyfLSuNQFdABEBAAG0
    CWRlbW8tdGVzdIjOBBMBCAA4FiEE8L4l7kQJL1kwGGOhLP4w7zUVVhIFAl0lr/EC
    GwMFCwkIBwIGFQoJCAsCBBYCAwECHgECF4AACgkQLP4w7zUVVhLBegP6AlZJBP2y
    jHwSo/t56ww4xBpfikXFD2tzvkJ7QmszOIqh9Bfa2HjvaO2yGVzijMudK++xTKdY
    M1Qo6Crn64vgqSc9crgn0ytVMVEpZ258H6z7qzB5pAETYMbwAaErib7IIrFEKzP7
    R0DayFML/OR0OD/xMv6104U9nIed4IbnF9O4jQRdJa/xAQQA47MvrpYH2/tJzV4h
    LVDBTkEg1AGaE5g4b74lotseEdQxv7bCd1ffqDxQT0xRT8EfpVMtK08Sy628oCyX
    K2De6HymHFGVlXptNCe5XSP7R6ES5PrybD4JwDFwnA0/Hy67l5XgSF5DAuA9X6KR
    RAJwM5koiv9QN/atx3axWGo74zkAEQEAAYi2BBgBCAAgFiEE8L4l7kQJL1kwGGOh
    LP4w7zUVVhIFAl0lr/ECGwwACgkQLP4w7zUVVhKGuwQAkE739R8M0lkzaDp7rCg4
    6kh78Q/x5LSB5vGOlvNa8yRRu5jFqGDQoSDsjMWCc9Ml5XLUeL4svtF/LhXIVcIn
    Ty9N1nD6MIBj7IwTmd/jVpbEeneRBKXxLOmiYJjLrOALAYyn8jNtm2yNsx4l2M/q
    vL7IbSgYhL+c8UMGGgEXcc8=
    =oWe9
    -----END PGP PUBLIC KEY BLOCK-----
  private_key: |
    -----BEGIN PGP PRIVATE KEY BLOCK-----

    lQIGBF0lr/EBBADSE2M0GkdbNi22bTWTY/RNMb5HVGfkc41HZo4j3FFE0zGdK+eg
    EBoMURbW9hzpYO6ghaWCcssytIJbD1eRZpbekzEUIrJFR9G5NBZ7rViuEt5wspyB
    RflPyDH7ZkvnwbXEuMCdpKp+hj5XkxoGz2jP0eSnB0cBFCBD8ny0rjUBXQARAQAB
    /gcDAlKGruMxrL/J6E4dbVFyLTlomBRYt9qEjyWupp4/n3VgFea5+eobfyf0S/LB
    4MNOEkJAo5/E+QaEE52dM6A2qWpqP1RnV5qaub14j1HnPXGFHt0kGz5JB5AmSY71
    /AxN68BEctYBu2cgMp45w80aBtzwDp9w5+ULMWRydczQxlu+SH3nSkYtaYYLlSJ1
    NH8k58iCkyOdDe3ycfwLQzOvGCBtp5evyNXjCks5d3antIquTX8N467X9Po4orT1
    13zihuSg5iKamQy1zCPxK8iv6FDCM9HJb2eam+VgPqDUNIGn771gpXIUC4E+j34P
    p269OpZzTElC/QVKUIfEQfXEAq+QacnH0baPuDZoBR68LRgvgaR0XufQ8scHj328
    BiT7ljMgbigtLYaivzeRCYM6ysKR+uOs86tWUTqp4eCLhAN0hqk1HB29tosr+rHh
    /dtznPDD7Az9paXb75lxk6W1D+s5mKIVeiVEUpEc9fgu9yYeU2ihMX+0CWRlbW8t
    dGVzdIjOBBMBCAA4FiEE8L4l7kQJL1kwGGOhLP4w7zUVVhIFAl0lr/ECGwMFCwkI
    BwIGFQoJCAsCBBYCAwECHgECF4AACgkQLP4w7zUVVhLBegP6AlZJBP2yjHwSo/t5
    6ww4xBpfikXFD2tzvkJ7QmszOIqh9Bfa2HjvaO2yGVzijMudK++xTKdYM1Qo6Crn
    64vgqSc9crgn0ytVMVEpZ258H6z7qzB5pAETYMbwAaErib7IIrFEKzP7R0DayFML
    /OR0OD/xMv6104U9nIed4IbnF9OdAgYEXSWv8QEEAOOzL66WB9v7Sc1eIS1QwU5B
    INQBmhOYOG++JaLbHhHUMb+2wndX36g8UE9MUU/BH6VTLStPEsutvKAslytg3uh8
    phxRlZV6bTQnuV0j+0ehEuT68mw+CcAxcJwNPx8uu5eV4EheQwLgPV+ikUQCcDOZ
    KIr/UDf2rcd2sVhqO+M5ABEBAAH+BwMC+3EwfUyyDVToW3srtcH2b4DMn5AsjdDZ
    2lxajGv4vk+/96s+/U1dmQofzmZ2Oo577zJHq2+R0qEZr/TtpXWpiUE7gKkTebKW
    oaAXT42kqNC7cFnWhNZkdRaY5WkeXXQfc4rMS6jtjY2h2du1uG76QkoODMT9iJXv
    PjCvPRHRHApLRZTaf7nCkbSqEJ+Eajglb0d3Jz9Y/oNSZ1rKhFOxV0/Z9GaJPvD3
    b5zbPjpoHTNtiXnERhaZDHFtL/2asq7Y4ECzi/HYSHjlTubkYYPW2WCJWSdvrnzm
    IxXhxAfIHG5nhXZxKf2NTCB4oL9siGvLlgM0dK3WPrPwrsqLTwTr0OclFt+kn21P
    RhImIuq79tLGfquhviqtvYN1MnSalFs4Qsp8tQo2UKfLScBeHSy+NYvvkgZZmkt4
    SoX76zXyZgI7w/B5jiW0vqUY7fYggn3uZ0508taHD8tZS9BE0MuLndZ3BAG6Vbsq
    /A+7HReh9qxHg0+PFYi2BBgBCAAgFiEE8L4l7kQJL1kwGGOhLP4w7zUVVhIFAl0l
    r/ECGwwACgkQLP4w7zUVVhKGuwQAkE739R8M0lkzaDp7rCg46kh78Q/x5LSB5vGO
    lvNa8yRRu5jFqGDQoSDsjMWCc9Ml5XLUeL4svtF/LhXIVcInTy9N1nD6MIBj7IwT
    md/jVpbEeneRBKXxLOmiYJjLrOALAYyn8jNtm2yNsx4l2M/qvL7IbSgYhL+c8UMG
    GgEXcc8=
    =bUJ2
    -----END PGP PRIVATE KEY BLOCK-----
  passphrase: 'password123'
